/*
SavePlus Installer
Drag and drop this file into Maya's viewport to install SavePlus.
Compatible with Maya 2016+
*/

global proc savePlusInstall() {
    string $whatIs = `whatIs savePlusInstall`;
    string $path = `substring $whatIs 25 999`;
    string $filename = `substitute "install_saveplus.mel" $path "install_saveplus.py"`;
    python("import imp;imp.load_source('_savePlusInstall', '"+$filename+"')");
}

savePlusInstall();